version: 2.1

############################################################################

config: &config
  working_directory: ~/repo
  docker:
    - image: cimg/node:25.9.0
  resource_class: small

persist-workspace: &persist-workspace
  persist_to_workspace:
    root: ~/
    paths:
      - repo

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/

# Cache node_modules
restore-dependencies-cache: &restore-dependencies-cache
  restore_cache:
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      # fallback to using the cache from the same branch
      - v1-dependencies-{{ .Branch }}-
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

save-dependencies-cache: &save-dependencies-cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

feature-branch: &feature-branch
  filters:
    branches:
      ignore:
        - /(custom_)?release\/.*/

env-context: &env-context
  context:
    - npm-js

############################################################################

jobs:
  build:
    <<: *config
    steps:
      - checkout

      - *restore-dependencies-cache

      # TODO PREAPPS-7520
      - run:
          name: Set correct npm version
          command: sudo npm install -g npm@11

      # install dependencies - do this AFTER we do the optional branch checkout of the api client
      - run:
          name: Install npm modules
          command: npm install --no-audit

      - *save-dependencies-cache

      - run:
          name: Build application code
          command: npm run build

      - *persist-workspace

  unit:
    <<: *config
    steps:
      - *attach-workspace
      - run:
          name: Run karma unit tests
          command: npm run test:unit

  lint:
    <<: *config
    steps:
      - *attach-workspace
      - run:
          name: Lint typescript source code
          command: npm run lint

  security-audit:
    <<: *config
    steps:
        - checkout

        - *restore-dependencies-cache

        # TODO PREAPPS-7520
        - run:
            name: Set correct npm version
            command: sudo npm install -g npm@11

        # Install dependencies - do this AFTER we do the optional branch checkout of the api client
        - run:
            name: Install npm modules
            command: npm install --no-audit

        - run:
            name: Run security audit
            command: npm run security:audit

  publish:
    <<: *config
    steps:
      - *attach-workspace

      - run:
          name: Setup npm authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > ~/.npmrc

      - run:
          name: Set dynamic prerelease version (no git tag)
          command: |
            SAFE_BRANCH=$(echo "$CIRCLE_BRANCH" | sed 's/\//-/g')
            SHORT_SHA=$(echo "$CIRCLE_SHA1" | cut -c1-7)

            npm version prerelease \
              --preid="${SAFE_BRANCH}.${SHORT_SHA}" \
              --no-git-tag-version

      - run:
          name: Publish to npm
          command: |
            SAFE_BRANCH=$(echo "$CIRCLE_BRANCH" | sed 's/\//-/g')
            if [ "$SAFE_BRANCH" = "master" ]; then
              npm publish --access public --tag beta
            else
              npm publish --access public --tag next
            fi

############################################################################

workflows:
  version: 2
  main:
    jobs:
      - build

      - security-audit

      - lint:
          requires:
            - build

      - unit:
          requires:
            - build

      - publish-approval:
          <<: *feature-branch
          type: approval
          requires:
            - build

      - publish:
          <<: *feature-branch
          <<: *env-context
          requires:
            - publish-approval

############################################################################
